// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATXUlF8fOo67p6myD7hZeBWOIlHidGr0c',
    appId: '1:826052245198:web:9ca58dc223f1633709c29f',
    messagingSenderId: '826052245198',
    projectId: 'edushare-5259a',
    authDomain: 'edushare-5259a.firebaseapp.com',
    storageBucket: 'edushare-5259a.firebasestorage.app',
    measurementId: 'G-BL92H56TDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9jc5EvyzqfFq0G8tlirv2fE05enXIf94',
    appId: '1:826052245198:android:27856495b345a5c109c29f',
    messagingSenderId: '826052245198',
    projectId: 'edushare-5259a',
    storageBucket: 'edushare-5259a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1iexMWqrAVN93z8u2bc5DLtUUIXIZI3Y',
    appId: '1:826052245198:ios:f52110dda1cdee8e09c29f',
    messagingSenderId: '826052245198',
    projectId: 'edushare-5259a',
    storageBucket: 'edushare-5259a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1iexMWqrAVN93z8u2bc5DLtUUIXIZI3Y',
    appId: '1:826052245198:ios:f52110dda1cdee8e09c29f',
    messagingSenderId: '826052245198',
    projectId: 'edushare-5259a',
    storageBucket: 'edushare-5259a.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATXUlF8fOo67p6myD7hZeBWOIlHidGr0c',
    appId: '1:826052245198:web:a2f79a8737a8514409c29f',
    messagingSenderId: '826052245198',
    projectId: 'edushare-5259a',
    authDomain: 'edushare-5259a.firebaseapp.com',
    storageBucket: 'edushare-5259a.firebasestorage.app',
    measurementId: 'G-QED678T0P1',
  );
}
